### ISSUE TITLE
Archive this?

### ISSUE THREAD

**Issue by gardar** [rndmh3ro/antsichaut-action#1]
Now that https://github.com/ansible-community/antsichaut/pull/43 has been merged, perhaps it would be a good idea to archive the project and note it in the readme that this has been migrated to https://github.com/ansible-community/antsichaut/

**Comment by rndmh3ro** [comment]
Yes, thanks. I already did this, however I needed to unarchive it again to delete the action from the marketplace. Then I forgot to archive it again.
